const nonTeachingStaff = [
  {
    code: "SASAMC001",
    name: "Mr. DEEPAK KUMAR YADAV",
    qualification: "Graduate",
    doj: "01-Dec-17",
    appointment: "Regular",
    designation: "Clerical staff for administrative and accounts services",
    department: "College Office",
  },
  {
    code: "SASAMC002",
    name: "Mr. DEEPAK KUMAR SRIWASTAV",
    qualification: "Graduate",
    doj: "03-Dec-18",
    appointment: "Regular",
    designation: "Clerical staff for administrative and accounts services",
    department: "College Office",
  },
  {
    code: "SASAMC003",
    name: "Mrs. RABIYA",
    qualification: "Less than 10th",
    doj: "30-Dec-20",
    appointment: "Regular",
    designation: "Multipurpose worker",
    department: "Herbal Garden",
  },
  {
    code: "SASAMC004",
    name: "Mrs. NOORJAHAN",
    qualification: "Less than 10th",
    doj: "02-Jan-21",
    appointment: "Regular",
    designation: "Others",
    department: "Others",
  },
  {
    code: "SASAMC005",
    name: "Mrs. SANJU",
    qualification: "Less than 10th",
    doj: "01-Apr-22",
    appointment: "Regular",
    designation: "Library Attendant or Peon",
    department: "Library",
  },
  {
    code: "SASAMC006",
    name: "Mr. KISHAN VISHWAKARMA",
    qualification: "Graduate",
    doj: "01-Apr-22",
    appointment: "Regular",
    designation: "Clerical staff for administrative and accounts services",
    department: "College Office",
  },
  {
    code: "SASAMC007",
    name: "Mrs. ASHIYA",
    qualification: "Less than 10th",
    doj: "10-Apr-22",
    appointment: "Regular",
    designation: "Attendant or Peon or Multipurpose Worker",
    department: "Roga Nidan evam Vikriti Vigyan",
  },
  {
    code: "SASAMC008",
    name: "Mr. UMA SHANKAR SINGH",
    qualification: "Graduate",
    doj: "10-Apr-22",
    appointment: "Regular",
    designation: "Lifter",
    department: "Rachna Sharir",
  },
  {
    code: "SASAMC009",
    name: "Mr. GYAN PRAKASH SHRIVASTAV",
    qualification: "Post-Graduate",
    doj: "01-Feb-23",
    appointment: "Regular",
    designation: "Librarian",
    department: "Library",
  },
  {
    code: "SASAMC010",
    name: "Mr. Nasiba Bano",
    qualification: "Graduate",
    doj: "01-Feb-23",
    appointment: "Regular",
    designation: "Museum Keeper",
    department: "Rachna Sharir",
  },
  {
    code: "SASAMC011",
    name: "Mrs. AMITA SINGH",
    qualification: "Graduate",
    doj: "02-Feb-23",
    appointment: "Regular",
    designation: "Assistant Librarian",
    department: "Library",
  },
  {
    code: "SASAMC012",
    name: "Mr. AVINASH KUMAR",
    qualification: "Other",
    doj: "01-Apr-23",
    appointment: "Regular",
    designation: "Laboratory Technician",
    department: "Roga Nidan evam Vikriti Vigyan",
  },
  {
    code: "SASAMC013",
    name: "Mr. ARVIND YADAV",
    qualification: "12",
    doj: "01-Jan-24",
    appointment: "Regular",
    designation: "Multipurpose worker",
    department: "Herbal Garden",
  },
  {
    code: "SASAMC014",
    name: "Ms. SMITA BHARGAV",
    qualification: "Graduate",
    doj: "01-Jan-24",
    appointment: "Regular",
    designation: "Clerical staff for administrative and accounts services",
    department: "College Office",
  },
  {
    code: "SASAMC015",
    name: "Mr. SHIV CHARAN",
    qualification: "Less than 10th",
    doj: "02-Jan-24",
    appointment: "Regular",
    designation: "Gardener",
    department: "Herbal Garden",
  },
  {
    code: "SASAMC016",
    name: "Mr. VIKASH KUMAR PATEL",
    qualification: "Other",
    doj: "04-Jan-24",
    appointment: "Regular",
    designation: "Laboratory Technician",
    department: "Kriya Sharir",
  },
  {
    code: "SASAMC017",
    name: "Mr. AKHILESH SHRIVASTAV",
    qualification: "Graduate",
    doj: "04-Jan-24",
    appointment: "Regular",
    designation: "Museum Keeper",
    department: "Kriya Sharir",
  },
  {
    code: "SASAMC018",
    name: "Ms. PINKI",
    qualification: "12",
    doj: "05-Jan-24",
    appointment: "Regular",
    designation: "Museum Keeper",
    department: "Agad Tantra evam Vidhi Vaidyaka",
  },
  {
    code: "SASAMC019",
    name: "Mr. KAUSHAL KUMAR",
    qualification: "Graduate",
    doj: "01-Sep-24",
    appointment: "Regular",
    designation: "Laboratory Assistant",
    department: "Rasa Shastra Evam Bhaishajya",
  },
  {
    code: "SASAMC020",
    name: "Mr. SANDEEP KUMAR SHARMA",
    qualification: "Other",
    doj: "01-Sep-24",
    appointment: "Regular",
    designation: "Museum Keeper",
    department: "Dravyaguna",
  },
  {
    code: "SASAMC021",
    name: "Mr. RITESH SHARMA",
    qualification: "12",
    doj: "01-Sep-24",
    appointment: "Regular",
    designation: "Attendant",
    department: "Kayachikitsa",
  },
  {
    code: "SASAMC022",
    name: "Mr. ABHISHEK GOSWAMI",
    qualification: "Graduate",
    doj: "15-Jan-25",
    appointment: "Regular",
    designation: "Laboratory Technician",
    department: "Rasa Shastra Evam Bhaishajya",
  },
  {
    code: "SASAMC023",
    name: "Mr. PUSHKAR SINGH",
    qualification: "Other",
    doj: "16-Jan-25",
    appointment: "Regular",
    designation: "Laboratory Technician",
    department: "Rachna Sharir",
  },
  {
    code: "SASAMC024",
    name: "Mr. SACHIN",
    qualification: "Other",
    doj: "16-Jan-25",
    appointment: "Regular",
    designation: "Attendant",
    department: "Swasthavritta and Yoga",
  },
  {
    code: "SASAMC025",
    name: "Mr. SHIVANS SINGH",
    qualification: "Other",
    doj: "17-Jan-25",
    appointment: "Regular",
    designation: "Laboratory Technician",
    department: "Roga Nidan evam Vikriti Vigyan",
  },
  {
    code: "SASAMC026",
    name: "MR. SHOBHIT KUMAR YADAV",
    qualification: "Other",
    doj: "17-Jan-25",
    appointment: "Regular",
    designation: "Laboratory Technician",
    department: "Dravyaguna",
  },
  {
    code: "SASAMC027",
    name: "Ms. GARIMA PANDEY",
    qualification: "Graduate",
    doj: "17-Jan-25",
    appointment: "Regular",
    designation: "Attendant",
    department: "Prasuti Tantra and Stri Roga",
  },
  {
    code: "SASAMC028",
    name: "Mr. NIRAJ YADAV",
    qualification: "Graduate",
    doj: "17-Jan-25",
    appointment: "Regular",
    designation: "Attendant",
    department: "Samhita and Siddhanta",
  },
];

export default nonTeachingStaff;
