const teachingStaff = [
  { name: "DR. VERTIKA SRIVASTAVA", designation: "Associate Professor / Reader", department: "Agad Tantra avum Vidhi Vaidyaka", code: "AYAT00145" },
  { name: "Dr. MANJEET KUMAR", designation: "Assistant Professor / Lecturer", department: "Agad Tantra avum Vidhi Vaidyaka", code: "AYAT00654" },
  { name: "DR. RASHMI VARSHNEY", designation: "Professor", department: "Ayurved Samhita & Siddhant", code: "AYSS01130" },
  { name: "Mr. DINESH SHANKAR TIWARI", designation: "Assistant Professor / Lecturer", department: "Ayurved Samhita & Siddhant", code: "AYSN00121" },
  { name: "DR. SEEMA KANAUJIA", designation: "Assistant Professor / Lecturer", department: "Ayurved Samhita & Siddhant", code: "AYSS01955" },
  { name: "Dr. CHITRALEKHA GAUR", designation: "Assistant Professor / Lecturer", department: "Ayurved Samhita & Siddhant", code: "AYSS01324" },
  { name: "Dr. RAMCHANDRA PANDEY", designation: "Professor", department: "Dravyaguna Vigyana", code: "AYDG01389" },
  { name: "DR. LALIT NAGAR", designation: "Assistant Professor / Lecturer", department: "Dravyaguna Vigyana", code: "AYDG02028" },
  { name: "Dr. PRIYANKA RAI", designation: "Professor", department: "Kaumarbhritya -Bala Roga", code: "AYKB00128" },
  { name: "DR. DHANANJAY PANDEY", designation: "Assistant Professor / Lecturer", department: "Kaumarbhritya -Bala Roga", code: "AYKB00993" },
  { name: "DR. SHASHI KANT PATHAK", designation: "Assistant Professor / Lecturer", department: "Kayachikitsa", code: "AYKC03747" },
  { name: "DR. ROHIT MAURYA", designation: "Associate Professor / Reader", department: "Kayachikitsa", code: "AYKC00684" },
  { name: "Dr. VINOD KUMAR SINGH", designation: "Professor", department: "Kayachikitsa", code: "AYKC01076" },
  { name: "DR. RASHMI SHARMA", designation: "Professor", department: "Kriya Sharir", code: "AYKS00089" },
  { name: "DR. SHILPANAND LAL YADAV", designation: "Assistant Professor / Lecturer", department: "Kriya Sharir", code: "AYKS00918" },
  { name: "DR. RAKESH MOHAN", designation: "Professor", department: "Panchakarma", code: "AYKC02153" },
  { name: "DR. RATNESH KUMAR DUBEY", designation: "Assistant Professor / Lecturer", department: "Panchakarma", code: "AYPK01070" },
  { name: "DR. KHUSBOO MIHRA", designation: "Assistant Professor / Lecturer", department: "Panchakarma", code: "AYPK01048" },
  { name: "Dr. RAJESH SINGH", designation: "Associate Professor / Reader", department: "Prasuti & Stri Roga", code: "AYST00161" },
  { name: "DR. RUBIKA DEVI", designation: "Associate Professor / Reader", department: "Prasuti & Stri Roga", code: "AYPS00872" },
  { name: "Dr. ASHOK KUMAR MAURYA", designation: "Assistant Professor / Lecturer", department: "Rachana Sharir", code: "AYRS01251" },
  { name: "Dr. MUKESH RAI", designation: "Professor", department: "Rachana Sharir", code: "AYST01453" },
  { name: "Dr. ASHA RAM VERMA", designation: "Professor", department: "Rasa Shastra & Bhaisajya Kalpana", code: "AYRB00908" },
  { name: "DR. GANGESHWAR TRIPATHI", designation: "Assistant Professor / Lecturer", department: "Rasa Shastra & Bhaisajya Kalpana", code: "AYRB01806" },
  { name: "Dr. SUVASHINI KUMAR PANDEY", designation: "Assistant Professor / Lecturer", department: "Rog Nidan avum Vikriti Vigyan", code: "AYRN00980" },
  { name: "Dr. DEVENDERA KUMAR SINGH", designation: "Professor", department: "Rog Nidan avum Vikriti Vigyan", code: "AYRN00528" },
  { name: "Dr. PRATIK KESHARI", designation: "Assistant Professor / Lecturer", department: "Shalakya Tantra", code: "AYST01753" },
  { name: "Dr. RITESH KUMAR PANDEY", designation: "Associate Professor / Reader", department: "Shalakya Tantra", code: "AYST00915" },
  { name: "Dr. SANJEEV SHARMA", designation: "Professor", department: "Shalyatantra + (Ksharsutra Lab.)", code: "AYST02263" },
  { name: "Dr. HARIOM SINGH", designation: "Associate Professor / Reader", department: "Shalyatantra + (Ksharsutra Lab.)", code: "AYST01075" },
  { name: "Dr. MASOORUDDIN", designation: "Associate Professor / Reader", department: "Shalyatantra + (Ksharsutra Lab.)", code: "AYST00015" },
  { name: "Dr. SACHIN THAPLIYAL", designation: "Assistant Professor / Lecturer", department: "Shalyatantra + (Ksharsutra Lab.)", code: "AYST02481" },
  { name: "Dr. AJIT SINGH", designation: "Associate Professor / Reader", department: "Swasthavritta & Yoga", code: "AYKC00043" },
  { name: "DR. CHANDRA PRATAP SINGH", designation: "Associate Professor / Reader", department: "Swasthavritta & Yoga", code: "AYKC00864" },
  { name: "DR. MAHESH RAI", designation: "Yoga Instructor", department: "Swasthavritta & Yoga", code: "NA" },
  { name: "HEM NARAYAN SINGH", designation: "Assistant Professor / Lecturer", department: "Biostatician", code: "NA" },
];

export default teachingStaff;
